apiVersion: v1
kind: Service
metadata:
  name: devop-frontend-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
    service.beta.kubernetes.io/aws-load-balancer-subnets: "subnet-0c4d266caf2fcfe7b,subnet-02cc1a0b546a2c3bd,subnet-02882351c007aa185"
spec:
  selector:
    app: devop-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer

  