# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  unit-tests:

    
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm run test:unit


      
  build:


    runs-on: ubuntu-latest
    
    needs: unit-tests
    
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - name: upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build
        path: dist
  
  cypress-run:


    runs-on: ubuntu-22.04
    

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node.js for cypress
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Install Vue CLI
        run: npm install -g @vue/cli 
      - name: build
        run: npm run build
      - name: Start server
        run: vue serve
      - name: wait for server
        run: npx wait-on http://localhost:4173
      - name: cypress run
        uses: cypress-io/github-action@v6
